name: Flybody
dname: fly_freejnt_amp
camera: 1
rendering_mjcf: ${paths.cwd_dir}/assets/fruitfly/fruitfly_force_pair_amp.xml
stac_path: ${paths.data_dir}/transform_tethered.p
clip_idx: amp_data.p
ref_traj_length: 5
env_args:
  clip_length: 1500
  mjcf_path: "${paths.cwd_dir}/assets/fruitfly/fruitfly_force_fast_amp.xml" 
  physics_timestep: 2e-4
  solver: cg
  iterations: 6
  ls_iterations: 6
  torque_actuators: True
  physics_steps_per_control_step: 10
  too_far_dist: 0.01
  bad_pose_dist: 5.0 
  bad_quat_dist: 0.075 
  ctrl_cost_weight: 0.02
  pos_reward_weight: 1.0
  quat_reward_weight: 1.0
  joint_reward_weight: 1.0
  angvel_reward_weight: 0.0
  bodypos_reward_weight: 0.0
  endeff_reward_weight: 1.0
  pos_scaling: 400.0
  quat_scaling: 4.0
  joint_scaling: 0.25
  angvel_scaling: 0.5
  bodypos_scaling: 8.0
  endeff_scaling: 10.0
  healthy_z_range: [-0.03, 0.1]
  reset_noise_scale: 1e-3
  ref_len: 5
  free_jnt: True
  inference_mode: False
  end_eff_names:
    - claw_T1_right
    - claw_T2_left
    - claw_T2_right
    - claw_T3_left
    - claw_T3_right
  body_names:
    - coxa_T1_right
    - femur_T1_right
    - tibia_T1_right
    - tarsus_T1_right
    - tarsus2_T1_right
    - tarsus3_T1_right
    - tarsus4_T1_right
    - claw_T1_right
    - coxa_T2_left
    - femur_T2_left
    - tibia_T2_left
    - tarsus_T2_left
    - tarsus2_T2_left
    - tarsus3_T2_left
    - tarsus4_T2_left
    - claw_T2_left
    - coxa_T2_right
    - femur_T2_right
    - tibia_T2_right
    - tarsus_T2_right
    - tarsus2_T2_right
    - tarsus3_T2_right
    - tarsus4_T2_right
    - claw_T2_right
    - coxa_T3_left
    - femur_T3_left
    - tibia_T3_left
    - tarsus_T3_left
    - tarsus2_T3_left
    - tarsus3_T3_left
    - tarsus4_T3_left
    - claw_T3_left
    - coxa_T3_right
    - femur_T3_right
    - tibia_T3_right
    - tarsus_T3_right
    - tarsus2_T3_right
    - tarsus3_T3_right
    - tarsus4_T3_right
    - claw_T3_right
  joint_names:
    - coxa_flexion_T1_right
    - coxa_twist_T1_right
    - femur_twist_T1_right
    - femur_T1_right
    - tibia_T1_right
    - tarsus_T1_right
    - coxa_flexion_T2_left
    - coxa_twist_T2_left
    - femur_twist_T2_left
    - femur_T2_left
    - tibia_T2_left
    - tarsus_T2_left
    - coxa_flexion_T2_right
    - coxa_twist_T2_right
    - femur_twist_T2_right
    - femur_T2_right
    - tibia_T2_right
    - tarsus_T2_right
    - coxa_flexion_T3_left
    - coxa_twist_T3_left
    - femur_twist_T3_left
    - femur_T3_left
    - tibia_T3_left
    - tarsus_T3_left
    - coxa_flexion_T3_right
    - coxa_twist_T3_right
    - femur_twist_T3_right
    - femur_T3_right
    - tibia_T3_right
    - tarsus_T3_right