name: train_fly_freejnt
version: ${resolve_default:debug,${..version}}
gpu: ${resolve_default:0,${..gpu}}
wandb_project: "eabe_debug"
env_name: fly_freejnt_clip
algo_name: ppo
task_name: ${dataset.dname}
note: 
num_envs: 1024 
num_timesteps: 10_000_000_000
eval_every: 200_000_000
num_resets_per_eval: 1
reward_scaling: 1
episode_length: 1001
normalize_observations: True
action_repeat: 1
clipping_epsilon: 0.2
unroll_length: 20
num_minibatches: 32
num_updates_per_batch: 8
discounting: 0.95
learning_rate: 1e-4
kl_weight: 1e-3
entropy_cost: 1e-2
batch_size: ${train.num_envs}
seed: 0
encoder_hidden_layer_sizes: [256, 256]
decoder_hidden_layer_sizes: [256, 256]
value_hidden_layer_sizes: [256, 256]
restore_checkpoint: ''
freeze_encoder: False
state_metric_list: 
  - pos_reward
  - quat_reward
  - joint_reward
  - angvel_reward
  - bodypos_reward
  - endeff_reward
  - reward_ctrlcost
  - too_far
  - bad_pose
  - bad_quat
  - termination
  - fall
info_metric_list: 
  - cur_frame
  - summed_pos_distance
  - quat_distance
  - joint_distance
  - angvel_distance
  - bodypos_distance
  - endeff_distance